### ISSUE TITLE
Error loading Addon - Classic Era

### ISSUE THREAD

**Issue by padkipz** [NumyAddon/UnifiedProfileManager#2]
Hi, 

I'm trying to load the addon currently on Classic Era, but I'm getting the error:

```
27x ...dOns/UnifiedProfileManager/UnifiedProfileManager.lua:7: Cannot find a library instance of "LibDualSpec-1.0".
[string "=[C]"]: in function 'error'
[string "@Ace3/LibStub/LibStub.lua"]:23: in function 'LibStub'
[string "@UnifiedProfileManager/UnifiedProfileManager.lua"]:7: in main chunk

Locals:
(*temporary) = "Cannot find a library instance of "LibDualSpec-1.0"."
```

I've checked, and I can see LibDualSpec-1.0 in the libs folder. I've also tested it on Classic Cata, and it works without any issues

**Comment by Numynum** [comment]
should be fixed in next release
apparently it only loads on classic era Season of Discovery 🤷‍♂️
